# Name you want to appear with. This can be whatever name/alias makes you most comfortable.
# Mandatory
name = "Nathan Graule"

# File name of your profile picture if you uploaded one
# If you provide a file, be mindful of its size
# If you also add your github profile, you can use "GitHub" to use your GitHub profile picture
# This can be any image that follows our code of conduct.
# Optional
profile-picture = "GitHub"

# Short presentation of yourself. This has a limit of 180 characters.
# Optional
bio = "Passionate about both graphics and audio programming, game engines are literally the best of both worlds!"

# Social links

# Will link to https://github.com/<username>
# Optional
github = "solarliner"

discord = "solarliner"
# This allows direct linking to your profile for people with a shared server
# https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
# Optional
discord-userid = "127826958758182912"

## Will link to https://<instance.com>/@<username>
# Optional
mastodon = "@solarliner@mastodon.social"

## Free link, will be displayed as is
# Optional
website = "https://solarliner.dev"
